global:
  resolve_timeout: 5m

route:
  receiver: 'email-alert'

receivers:
  - name: 'email-alert'
    email_configs:
      - to: 'khalloulimonem32@gmail.com'
        from: 'test02test023@gmail.com'
        smarthost: 'smtp.gmail.com'
        auth_username: 'test02test023@gmail.com'
        auth_password: 'mxtzrypmyujlszdo'
