name: CI/CD Azure Web Apps

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Login Azure avec Service Principal
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      # ---------------- Backend ----------------
      - name: Install backend dependencies
        run: |
          cd backend
          npm ci

      - name: Deploy Backend to Azure Web App
        run: |
          az webapp deploy --resource-group myapp-angular_group-b390 \
            --name myapp-backend \
            --src-path ./backend

      # ---------------- Frontend ----------------
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci
          npm run build

      - name: Deploy Frontend to Azure Web App
        run: |
          az webapp deploy --resource-group myapp-angular_group-b390 \
            --name myapp-frontend \
            --src-path ./frontend/dist/frontend
