name: CI/CD Azure Web Apps

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Login Azure via Service Principal
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # JSON complet du SP

      # ---------------- Backend ----------------
      - name: Install backend dependencies
        run: |
          cd backend
          npm ci

      - name: Deploy Backend to Azure Web App
        run: |
          az webapp deploy --resource-group MP2L \
            --name MP2LBackInstance \
            --src-path ./backend

      # ---------------- Frontend ----------------
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci
          npm run build

      - name: Deploy Frontend to Azure Web App
        run: |
          az webapp deploy --resource-group MP2L \
            --name myapp-angular-frontend \
            --src-path ./frontend/dist/frontend
